### ISSUE TITLE
Please bump tiny to 1.5.1 and push new pod

### ISSUE THREAD

**Issue by ssoper** [dtorres/OLImageView#63]
Been seeing this warning for several months now
`OLImageView/OLImage.m:306:26: warning: unused function 'OLCreateDecodedCGImageFromCGImage' [-Wunused-function]`

I don't see the method in OLImage.m anymore so I can only assume it's been fixed. Can we get a new version of the pod to reflect this change? Thanks.

**Comment by ArtSabintsev** [comment]
+1

**Comment by anscho** [comment]
+1

**Comment by dtorres** [comment]
Will do. No need for more +1 ;)

--
Diego Torres.

**Comment by dtorres** [comment]
Here you go: https://raw.githubusercontent.com/CocoaPods/Specs/f52fee715632d5f8b6e2a1060c96d982ac6d42d7/Specs/OLImageView/1.5.1/OLImageView.podspec.json

**Comment by ssoper** [comment]
Thank you! :boat:
